// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/indexer/v1/indexer.proto

package indexerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChainType represents the blockchain type
type ChainType int32

const (
	ChainType_CHAIN_TYPE_UNSPECIFIED ChainType = 0
	ChainType_CHAIN_TYPE_EVM         ChainType = 1
	ChainType_CHAIN_TYPE_SOLANA      ChainType = 2
	ChainType_CHAIN_TYPE_COSMOS      ChainType = 3
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "CHAIN_TYPE_UNSPECIFIED",
		1: "CHAIN_TYPE_EVM",
		2: "CHAIN_TYPE_SOLANA",
		3: "CHAIN_TYPE_COSMOS",
	}
	ChainType_value = map[string]int32{
		"CHAIN_TYPE_UNSPECIFIED": 0,
		"CHAIN_TYPE_EVM":         1,
		"CHAIN_TYPE_SOLANA":      2,
		"CHAIN_TYPE_COSMOS":      3,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_indexer_v1_indexer_proto_enumTypes[0].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_api_proto_indexer_v1_indexer_proto_enumTypes[0]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{0}
}

// ChainStatus represents the chain indexing status
type ChainStatus int32

const (
	ChainStatus_CHAIN_STATUS_UNSPECIFIED ChainStatus = 0
	ChainStatus_CHAIN_STATUS_ACTIVE      ChainStatus = 1
	ChainStatus_CHAIN_STATUS_INACTIVE    ChainStatus = 2
	ChainStatus_CHAIN_STATUS_SYNCING     ChainStatus = 3
	ChainStatus_CHAIN_STATUS_ERROR       ChainStatus = 4
)

// Enum value maps for ChainStatus.
var (
	ChainStatus_name = map[int32]string{
		0: "CHAIN_STATUS_UNSPECIFIED",
		1: "CHAIN_STATUS_ACTIVE",
		2: "CHAIN_STATUS_INACTIVE",
		3: "CHAIN_STATUS_SYNCING",
		4: "CHAIN_STATUS_ERROR",
	}
	ChainStatus_value = map[string]int32{
		"CHAIN_STATUS_UNSPECIFIED": 0,
		"CHAIN_STATUS_ACTIVE":      1,
		"CHAIN_STATUS_INACTIVE":    2,
		"CHAIN_STATUS_SYNCING":     3,
		"CHAIN_STATUS_ERROR":       4,
	}
)

func (x ChainStatus) Enum() *ChainStatus {
	p := new(ChainStatus)
	*p = x
	return p
}

func (x ChainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_indexer_v1_indexer_proto_enumTypes[1].Descriptor()
}

func (ChainStatus) Type() protoreflect.EnumType {
	return &file_api_proto_indexer_v1_indexer_proto_enumTypes[1]
}

func (x ChainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainStatus.Descriptor instead.
func (ChainStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{1}
}

// TransactionStatus represents transaction execution status
type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_SUCCESS     TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 3
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_SUCCESS",
		3: "TRANSACTION_STATUS_FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_SUCCESS":     2,
		"TRANSACTION_STATUS_FAILED":      3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_indexer_v1_indexer_proto_enumTypes[2].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_indexer_v1_indexer_proto_enumTypes[2]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{2}
}

// Chain information
type Chain struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChainId            string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType          ChainType              `protobuf:"varint,2,opt,name=chain_type,json=chainType,proto3,enum=indexer.v1.ChainType" json:"chain_type,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Network            string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Status             ChainStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=indexer.v1.ChainStatus" json:"status,omitempty"`
	StartBlock         uint64                 `protobuf:"varint,6,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	LatestIndexedBlock uint64                 `protobuf:"varint,7,opt,name=latest_indexed_block,json=latestIndexedBlock,proto3" json:"latest_indexed_block,omitempty"`
	LatestChainBlock   uint64                 `protobuf:"varint,8,opt,name=latest_chain_block,json=latestChainBlock,proto3" json:"latest_chain_block,omitempty"`
	LastUpdated        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *Chain) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Chain) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_CHAIN_TYPE_UNSPECIFIED
}

func (x *Chain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chain) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Chain) GetStatus() ChainStatus {
	if x != nil {
		return x.Status
	}
	return ChainStatus_CHAIN_STATUS_UNSPECIFIED
}

func (x *Chain) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *Chain) GetLatestIndexedBlock() uint64 {
	if x != nil {
		return x.LatestIndexedBlock
	}
	return 0
}

func (x *Chain) GetLatestChainBlock() uint64 {
	if x != nil {
		return x.LatestChainBlock
	}
	return 0
}

func (x *Chain) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

// Block represents a blockchain block
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType     ChainType              `protobuf:"varint,2,opt,name=chain_type,json=chainType,proto3,enum=indexer.v1.ChainType" json:"chain_type,omitempty"`
	Number        uint64                 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash    string                 `protobuf:"bytes,5,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,7,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Miner         string                 `protobuf:"bytes,9,opt,name=miner,proto3" json:"miner,omitempty"`
	TxCount       int32                  `protobuf:"varint,10,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,11,rep,name=transactions,proto3" json:"transactions,omitempty"`
	IndexedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Block) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_CHAIN_TYPE_UNSPECIFIED
}

func (x *Block) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *Block) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Block) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Block) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Block) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

func (x *Block) GetTxCount() int32 {
	if x != nil {
		return x.TxCount
	}
	return 0
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

// Transaction represents a blockchain transaction
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChainId         string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Hash            string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,3,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash       string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockTimestamp  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	TxIndex         uint32                 `protobuf:"varint,6,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	From            string                 `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	Value           string                 `protobuf:"bytes,9,opt,name=value,proto3" json:"value,omitempty"`
	GasPrice        string                 `protobuf:"bytes,10,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasUsed         uint64                 `protobuf:"varint,11,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Nonce           uint64                 `protobuf:"varint,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Input           []byte                 `protobuf:"bytes,13,opt,name=input,proto3" json:"input,omitempty"`
	Status          TransactionStatus      `protobuf:"varint,14,opt,name=status,proto3,enum=indexer.v1.TransactionStatus" json:"status,omitempty"`
	ContractAddress string                 `protobuf:"bytes,15,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Logs            []*Log                 `protobuf:"bytes,16,rep,name=logs,proto3" json:"logs,omitempty"`
	IndexedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Transaction) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *Transaction) GetBlockTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BlockTimestamp
	}
	return nil
}

func (x *Transaction) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transaction) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *Transaction) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *Transaction) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Transaction) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

// Log represents a transaction event log
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	LogIndex      uint32                 `protobuf:"varint,4,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Log) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetLogIndex() uint32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

// Progress represents indexing progress
type Progress struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ChainId                  string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType                string                 `protobuf:"bytes,2,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	LatestIndexedBlock       uint64                 `protobuf:"varint,3,opt,name=latest_indexed_block,json=latestIndexedBlock,proto3" json:"latest_indexed_block,omitempty"`
	LatestChainBlock         uint64                 `protobuf:"varint,4,opt,name=latest_chain_block,json=latestChainBlock,proto3" json:"latest_chain_block,omitempty"`
	TargetBlock              uint64                 `protobuf:"varint,5,opt,name=target_block,json=targetBlock,proto3" json:"target_block,omitempty"`
	StartBlock               uint64                 `protobuf:"varint,6,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	BlocksBehind             uint64                 `protobuf:"varint,7,opt,name=blocks_behind,json=blocksBehind,proto3" json:"blocks_behind,omitempty"`
	ProgressPercentage       float64                `protobuf:"fixed64,8,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	BlocksPerSecond          float64                `protobuf:"fixed64,9,opt,name=blocks_per_second,json=blocksPerSecond,proto3" json:"blocks_per_second,omitempty"`
	EstimatedTimeLeftSeconds int64                  `protobuf:"varint,10,opt,name=estimated_time_left_seconds,json=estimatedTimeLeftSeconds,proto3" json:"estimated_time_left_seconds,omitempty"`
	LastUpdated              *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Status                   string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *Progress) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Progress) GetChainType() string {
	if x != nil {
		return x.ChainType
	}
	return ""
}

func (x *Progress) GetLatestIndexedBlock() uint64 {
	if x != nil {
		return x.LatestIndexedBlock
	}
	return 0
}

func (x *Progress) GetLatestChainBlock() uint64 {
	if x != nil {
		return x.LatestChainBlock
	}
	return 0
}

func (x *Progress) GetTargetBlock() uint64 {
	if x != nil {
		return x.TargetBlock
	}
	return 0
}

func (x *Progress) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *Progress) GetBlocksBehind() uint64 {
	if x != nil {
		return x.BlocksBehind
	}
	return 0
}

func (x *Progress) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *Progress) GetBlocksPerSecond() float64 {
	if x != nil {
		return x.BlocksPerSecond
	}
	return 0
}

func (x *Progress) GetEstimatedTimeLeftSeconds() int64 {
	if x != nil {
		return x.EstimatedTimeLeftSeconds
	}
	return 0
}

func (x *Progress) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Progress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Gap represents a gap in indexed blocks
type Gap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	StartBlock    uint64                 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock      uint64                 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gap) Reset() {
	*x = Gap{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gap) ProtoMessage() {}

func (x *Gap) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gap.ProtoReflect.Descriptor instead.
func (*Gap) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{5}
}

func (x *Gap) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *Gap) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *Gap) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

func (x *Gap) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Statistics
type Stats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalBlocks       uint64                 `protobuf:"varint,1,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	TotalTransactions uint64                 `protobuf:"varint,2,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	ChainsIndexed     int32                  `protobuf:"varint,3,opt,name=chains_indexed,json=chainsIndexed,proto3" json:"chains_indexed,omitempty"`
	AverageBlockTime  float64                `protobuf:"fixed64,4,opt,name=average_block_time,json=averageBlockTime,proto3" json:"average_block_time,omitempty"`
	AverageTxPerBlock float64                `protobuf:"fixed64,5,opt,name=average_tx_per_block,json=averageTxPerBlock,proto3" json:"average_tx_per_block,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{6}
}

func (x *Stats) GetTotalBlocks() uint64 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *Stats) GetTotalTransactions() uint64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *Stats) GetChainsIndexed() int32 {
	if x != nil {
		return x.ChainsIndexed
	}
	return 0
}

func (x *Stats) GetAverageBlockTime() float64 {
	if x != nil {
		return x.AverageBlockTime
	}
	return 0
}

func (x *Stats) GetAverageTxPerBlock() float64 {
	if x != nil {
		return x.AverageTxPerBlock
	}
	return 0
}

// Pagination
type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasNextPage     bool                   `protobuf:"varint,1,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	HasPreviousPage bool                   `protobuf:"varint,2,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	StartCursor     string                 `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	EndCursor       string                 `protobuf:"bytes,4,opt,name=end_cursor,json=endCursor,proto3" json:"end_cursor,omitempty"`
	TotalCount      int32                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{7}
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil {
		return x.EndCursor
	}
	return ""
}

func (x *PageInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetChainRequest
type GetChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainRequest) Reset() {
	*x = GetChainRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainRequest) ProtoMessage() {}

func (x *GetChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainRequest.ProtoReflect.Descriptor instead.
func (*GetChainRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{8}
}

func (x *GetChainRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// GetChainResponse
type GetChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         *Chain                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainResponse) Reset() {
	*x = GetChainResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainResponse) ProtoMessage() {}

func (x *GetChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainResponse.ProtoReflect.Descriptor instead.
func (*GetChainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{9}
}

func (x *GetChainResponse) GetChain() *Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

// ListChainsRequest
type ListChainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsRequest) Reset() {
	*x = ListChainsRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsRequest) ProtoMessage() {}

func (x *ListChainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsRequest.ProtoReflect.Descriptor instead.
func (*ListChainsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{10}
}

// ListChainsResponse
type ListChainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*Chain               `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChainsResponse) Reset() {
	*x = ListChainsResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChainsResponse) ProtoMessage() {}

func (x *ListChainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChainsResponse.ProtoReflect.Descriptor instead.
func (*ListChainsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{11}
}

func (x *ListChainsResponse) GetChains() []*Chain {
	if x != nil {
		return x.Chains
	}
	return nil
}

// GetBlockRequest
type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlockRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetBlockRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

// GetBlockResponse
type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// GetBlockByHashRequest
type GetBlockByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHashRequest) Reset() {
	*x = GetBlockByHashRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHashRequest) ProtoMessage() {}

func (x *GetBlockByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHashRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{14}
}

func (x *GetBlockByHashRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetBlockByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// GetBlockByHashResponse
type GetBlockByHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHashResponse) Reset() {
	*x = GetBlockByHashResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHashResponse) ProtoMessage() {}

func (x *GetBlockByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHashResponse.ProtoReflect.Descriptor instead.
func (*GetBlockByHashResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{15}
}

func (x *GetBlockByHashResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// ListBlocksRequest
type ListBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	StartBlock    uint64                 `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock      uint64                 `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{16}
}

func (x *ListBlocksRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ListBlocksRequest) GetStartBlock() uint64 {
	if x != nil {
		return x.StartBlock
	}
	return 0
}

func (x *ListBlocksRequest) GetEndBlock() uint64 {
	if x != nil {
		return x.EndBlock
	}
	return 0
}

func (x *ListBlocksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBlocksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListBlocksResponse
type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{17}
}

func (x *ListBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ListBlocksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListBlocksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetLatestBlockRequest
type GetLatestBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockRequest) Reset() {
	*x = GetLatestBlockRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockRequest) ProtoMessage() {}

func (x *GetLatestBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockRequest.ProtoReflect.Descriptor instead.
func (*GetLatestBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{18}
}

func (x *GetLatestBlockRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// GetLatestBlockResponse
type GetLatestBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockResponse) Reset() {
	*x = GetLatestBlockResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockResponse) ProtoMessage() {}

func (x *GetLatestBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockResponse.ProtoReflect.Descriptor instead.
func (*GetLatestBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{19}
}

func (x *GetLatestBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// GetTransactionRequest
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{20}
}

func (x *GetTransactionRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *GetTransactionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// GetTransactionResponse
type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{21}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// ListTransactionsByBlockRequest
type ListTransactionsByBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsByBlockRequest) Reset() {
	*x = ListTransactionsByBlockRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsByBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsByBlockRequest) ProtoMessage() {}

func (x *ListTransactionsByBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsByBlockRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsByBlockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{22}
}

func (x *ListTransactionsByBlockRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ListTransactionsByBlockRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

// ListTransactionsByBlockResponse
type ListTransactionsByBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsByBlockResponse) Reset() {
	*x = ListTransactionsByBlockResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsByBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsByBlockResponse) ProtoMessage() {}

func (x *ListTransactionsByBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsByBlockResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsByBlockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{23}
}

func (x *ListTransactionsByBlockResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// ListTransactionsByAddressRequest
type ListTransactionsByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsByAddressRequest) Reset() {
	*x = ListTransactionsByAddressRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsByAddressRequest) ProtoMessage() {}

func (x *ListTransactionsByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsByAddressRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsByAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{24}
}

func (x *ListTransactionsByAddressRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ListTransactionsByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ListTransactionsByAddressRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsByAddressRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListTransactionsByAddressResponse
type ListTransactionsByAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsByAddressResponse) Reset() {
	*x = ListTransactionsByAddressResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsByAddressResponse) ProtoMessage() {}

func (x *ListTransactionsByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsByAddressResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsByAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{25}
}

func (x *ListTransactionsByAddressResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsByAddressResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTransactionsByAddressResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetProgressRequest
type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{26}
}

func (x *GetProgressRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// GetProgressResponse
type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *Progress              `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{27}
}

func (x *GetProgressResponse) GetProgress() *Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

// ListGapsRequest
type ListGapsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGapsRequest) Reset() {
	*x = ListGapsRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGapsRequest) ProtoMessage() {}

func (x *ListGapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGapsRequest.ProtoReflect.Descriptor instead.
func (*ListGapsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{28}
}

func (x *ListGapsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// ListGapsResponse
type ListGapsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gaps          []*Gap                 `protobuf:"bytes,1,rep,name=gaps,proto3" json:"gaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGapsResponse) Reset() {
	*x = ListGapsResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGapsResponse) ProtoMessage() {}

func (x *ListGapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGapsResponse.ProtoReflect.Descriptor instead.
func (*ListGapsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{29}
}

func (x *ListGapsResponse) GetGaps() []*Gap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

// GetStatsRequest
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{30}
}

func (x *GetStatsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// GetStatsResponse
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{31}
}

func (x *GetStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// StreamBlocksRequest
type StreamBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksRequest.ProtoReflect.Descriptor instead.
func (*StreamBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{32}
}

func (x *StreamBlocksRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// StreamTransactionsRequest
type StreamTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTransactionsRequest) Reset() {
	*x = StreamTransactionsRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTransactionsRequest) ProtoMessage() {}

func (x *StreamTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTransactionsRequest.ProtoReflect.Descriptor instead.
func (*StreamTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{33}
}

func (x *StreamTransactionsRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// StreamProgressRequest
type StreamProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamProgressRequest) Reset() {
	*x = StreamProgressRequest{}
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProgressRequest) ProtoMessage() {}

func (x *StreamProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_indexer_v1_indexer_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProgressRequest.ProtoReflect.Descriptor instead.
func (*StreamProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_indexer_v1_indexer_proto_rawDescGZIP(), []int{34}
}

func (x *StreamProgressRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

var File_api_proto_indexer_v1_indexer_proto protoreflect.FileDescriptor

const file_api_proto_indexer_v1_indexer_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/indexer/v1/indexer.proto\x12\n" +
	"indexer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x02\n" +
	"\x05Chain\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x124\n" +
	"\n" +
	"chain_type\x18\x02 \x01(\x0e2\x15.indexer.v1.ChainTypeR\tchainType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.indexer.v1.ChainStatusR\x06status\x12\x1f\n" +
	"\vstart_block\x18\x06 \x01(\x04R\n" +
	"startBlock\x120\n" +
	"\x14latest_indexed_block\x18\a \x01(\x04R\x12latestIndexedBlock\x12,\n" +
	"\x12latest_chain_block\x18\b \x01(\x04R\x10latestChainBlock\x12=\n" +
	"\flast_updated\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\xc0\x03\n" +
	"\x05Block\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x124\n" +
	"\n" +
	"chain_type\x18\x02 \x01(\x0e2\x15.indexer.v1.ChainTypeR\tchainType\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1f\n" +
	"\vparent_hash\x18\x05 \x01(\tR\n" +
	"parentHash\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\bgas_used\x18\a \x01(\x04R\agasUsed\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x14\n" +
	"\x05miner\x18\t \x01(\tR\x05miner\x12\x19\n" +
	"\btx_count\x18\n" +
	" \x01(\x05R\atxCount\x12;\n" +
	"\ftransactions\x18\v \x03(\v2\x17.indexer.v1.TransactionR\ftransactions\x129\n" +
	"\n" +
	"indexed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt\"\xbe\x04\n" +
	"\vTransaction\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12!\n" +
	"\fblock_number\x18\x03 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\x12C\n" +
	"\x0fblock_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eblockTimestamp\x12\x19\n" +
	"\btx_index\x18\x06 \x01(\rR\atxIndex\x12\x12\n" +
	"\x04from\x18\a \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\b \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\t \x01(\tR\x05value\x12\x1b\n" +
	"\tgas_price\x18\n" +
	" \x01(\tR\bgasPrice\x12\x19\n" +
	"\bgas_used\x18\v \x01(\x04R\agasUsed\x12\x14\n" +
	"\x05nonce\x18\f \x01(\x04R\x05nonce\x12\x14\n" +
	"\x05input\x18\r \x01(\fR\x05input\x125\n" +
	"\x06status\x18\x0e \x01(\x0e2\x1d.indexer.v1.TransactionStatusR\x06status\x12)\n" +
	"\x10contract_address\x18\x0f \x01(\tR\x0fcontractAddress\x12#\n" +
	"\x04logs\x18\x10 \x03(\v2\x0f.indexer.v1.LogR\x04logs\x129\n" +
	"\n" +
	"indexed_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt\"h\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\tlog_index\x18\x04 \x01(\rR\blogIndex\"\x80\x04\n" +
	"\bProgress\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1d\n" +
	"\n" +
	"chain_type\x18\x02 \x01(\tR\tchainType\x120\n" +
	"\x14latest_indexed_block\x18\x03 \x01(\x04R\x12latestIndexedBlock\x12,\n" +
	"\x12latest_chain_block\x18\x04 \x01(\x04R\x10latestChainBlock\x12!\n" +
	"\ftarget_block\x18\x05 \x01(\x04R\vtargetBlock\x12\x1f\n" +
	"\vstart_block\x18\x06 \x01(\x04R\n" +
	"startBlock\x12#\n" +
	"\rblocks_behind\x18\a \x01(\x04R\fblocksBehind\x12/\n" +
	"\x13progress_percentage\x18\b \x01(\x01R\x12progressPercentage\x12*\n" +
	"\x11blocks_per_second\x18\t \x01(\x01R\x0fblocksPerSecond\x12=\n" +
	"\x1bestimated_time_left_seconds\x18\n" +
	" \x01(\x03R\x18estimatedTimeLeftSeconds\x12=\n" +
	"\flast_updated\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\"r\n" +
	"\x03Gap\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1b\n" +
	"\tend_block\x18\x03 \x01(\x04R\bendBlock\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\"\xdf\x01\n" +
	"\x05Stats\x12!\n" +
	"\ftotal_blocks\x18\x01 \x01(\x04R\vtotalBlocks\x12-\n" +
	"\x12total_transactions\x18\x02 \x01(\x04R\x11totalTransactions\x12%\n" +
	"\x0echains_indexed\x18\x03 \x01(\x05R\rchainsIndexed\x12,\n" +
	"\x12average_block_time\x18\x04 \x01(\x01R\x10averageBlockTime\x12/\n" +
	"\x14average_tx_per_block\x18\x05 \x01(\x01R\x11averageTxPerBlock\"\xbd\x01\n" +
	"\bPageInfo\x12\"\n" +
	"\rhas_next_page\x18\x01 \x01(\bR\vhasNextPage\x12*\n" +
	"\x11has_previous_page\x18\x02 \x01(\bR\x0fhasPreviousPage\x12!\n" +
	"\fstart_cursor\x18\x03 \x01(\tR\vstartCursor\x12\x1d\n" +
	"\n" +
	"end_cursor\x18\x04 \x01(\tR\tendCursor\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount\",\n" +
	"\x0fGetChainRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\";\n" +
	"\x10GetChainResponse\x12'\n" +
	"\x05chain\x18\x01 \x01(\v2\x11.indexer.v1.ChainR\x05chain\"\x13\n" +
	"\x11ListChainsRequest\"?\n" +
	"\x12ListChainsResponse\x12)\n" +
	"\x06chains\x18\x01 \x03(\v2\x11.indexer.v1.ChainR\x06chains\"D\n" +
	"\x0fGetBlockRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\";\n" +
	"\x10GetBlockResponse\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.indexer.v1.BlockR\x05block\"F\n" +
	"\x15GetBlockByHashRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"A\n" +
	"\x16GetBlockByHashResponse\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.indexer.v1.BlockR\x05block\"\xa8\x01\n" +
	"\x11ListBlocksRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1f\n" +
	"\vstart_block\x18\x02 \x01(\x04R\n" +
	"startBlock\x12\x1b\n" +
	"\tend_block\x18\x03 \x01(\x04R\bendBlock\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x88\x01\n" +
	"\x12ListBlocksResponse\x12)\n" +
	"\x06blocks\x18\x01 \x03(\v2\x11.indexer.v1.BlockR\x06blocks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"2\n" +
	"\x15GetLatestBlockRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"A\n" +
	"\x16GetLatestBlockResponse\x12'\n" +
	"\x05block\x18\x01 \x01(\v2\x11.indexer.v1.BlockR\x05block\"F\n" +
	"\x15GetTransactionRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"S\n" +
	"\x16GetTransactionResponse\x129\n" +
	"\vtransaction\x18\x01 \x01(\v2\x17.indexer.v1.TransactionR\vtransaction\"^\n" +
	"\x1eListTransactionsByBlockRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\"^\n" +
	"\x1fListTransactionsByBlockResponse\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.indexer.v1.TransactionR\ftransactions\"\x93\x01\n" +
	" ListTransactionsByAddressRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xa9\x01\n" +
	"!ListTransactionsByAddressResponse\x12;\n" +
	"\ftransactions\x18\x01 \x03(\v2\x17.indexer.v1.TransactionR\ftransactions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"/\n" +
	"\x12GetProgressRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"G\n" +
	"\x13GetProgressResponse\x120\n" +
	"\bprogress\x18\x01 \x01(\v2\x14.indexer.v1.ProgressR\bprogress\",\n" +
	"\x0fListGapsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"7\n" +
	"\x10ListGapsResponse\x12#\n" +
	"\x04gaps\x18\x01 \x03(\v2\x0f.indexer.v1.GapR\x04gaps\",\n" +
	"\x0fGetStatsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\";\n" +
	"\x10GetStatsResponse\x12'\n" +
	"\x05stats\x18\x01 \x01(\v2\x11.indexer.v1.StatsR\x05stats\"0\n" +
	"\x13StreamBlocksRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"6\n" +
	"\x19StreamTransactionsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\"2\n" +
	"\x15StreamProgressRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId*i\n" +
	"\tChainType\x12\x1a\n" +
	"\x16CHAIN_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCHAIN_TYPE_EVM\x10\x01\x12\x15\n" +
	"\x11CHAIN_TYPE_SOLANA\x10\x02\x12\x15\n" +
	"\x11CHAIN_TYPE_COSMOS\x10\x03*\x91\x01\n" +
	"\vChainStatus\x12\x1c\n" +
	"\x18CHAIN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CHAIN_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15CHAIN_STATUS_INACTIVE\x10\x02\x12\x18\n" +
	"\x14CHAIN_STATUS_SYNCING\x10\x03\x12\x16\n" +
	"\x12CHAIN_STATUS_ERROR\x10\x04*\x96\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x032\xfa\t\n" +
	"\x0eIndexerService\x12E\n" +
	"\bGetChain\x12\x1b.indexer.v1.GetChainRequest\x1a\x1c.indexer.v1.GetChainResponse\x12K\n" +
	"\n" +
	"ListChains\x12\x1d.indexer.v1.ListChainsRequest\x1a\x1e.indexer.v1.ListChainsResponse\x12E\n" +
	"\bGetBlock\x12\x1b.indexer.v1.GetBlockRequest\x1a\x1c.indexer.v1.GetBlockResponse\x12W\n" +
	"\x0eGetBlockByHash\x12!.indexer.v1.GetBlockByHashRequest\x1a\".indexer.v1.GetBlockByHashResponse\x12K\n" +
	"\n" +
	"ListBlocks\x12\x1d.indexer.v1.ListBlocksRequest\x1a\x1e.indexer.v1.ListBlocksResponse\x12W\n" +
	"\x0eGetLatestBlock\x12!.indexer.v1.GetLatestBlockRequest\x1a\".indexer.v1.GetLatestBlockResponse\x12W\n" +
	"\x0eGetTransaction\x12!.indexer.v1.GetTransactionRequest\x1a\".indexer.v1.GetTransactionResponse\x12r\n" +
	"\x17ListTransactionsByBlock\x12*.indexer.v1.ListTransactionsByBlockRequest\x1a+.indexer.v1.ListTransactionsByBlockResponse\x12x\n" +
	"\x19ListTransactionsByAddress\x12,.indexer.v1.ListTransactionsByAddressRequest\x1a-.indexer.v1.ListTransactionsByAddressResponse\x12N\n" +
	"\vGetProgress\x12\x1e.indexer.v1.GetProgressRequest\x1a\x1f.indexer.v1.GetProgressResponse\x12E\n" +
	"\bListGaps\x12\x1b.indexer.v1.ListGapsRequest\x1a\x1c.indexer.v1.ListGapsResponse\x12E\n" +
	"\bGetStats\x12\x1b.indexer.v1.GetStatsRequest\x1a\x1c.indexer.v1.GetStatsResponse\x12D\n" +
	"\fStreamBlocks\x12\x1f.indexer.v1.StreamBlocksRequest\x1a\x11.indexer.v1.Block0\x01\x12V\n" +
	"\x12StreamTransactions\x12%.indexer.v1.StreamTransactionsRequest\x1a\x17.indexer.v1.Transaction0\x01\x12K\n" +
	"\x0eStreamProgress\x12!.indexer.v1.StreamProgressRequest\x1a\x14.indexer.v1.Progress0\x01BMZKgithub.com/sage-x-project/blockchain-indexer/api/proto/indexer/v1;indexerv1b\x06proto3"

var (
	file_api_proto_indexer_v1_indexer_proto_rawDescOnce sync.Once
	file_api_proto_indexer_v1_indexer_proto_rawDescData []byte
)

func file_api_proto_indexer_v1_indexer_proto_rawDescGZIP() []byte {
	file_api_proto_indexer_v1_indexer_proto_rawDescOnce.Do(func() {
		file_api_proto_indexer_v1_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_indexer_v1_indexer_proto_rawDesc), len(file_api_proto_indexer_v1_indexer_proto_rawDesc)))
	})
	return file_api_proto_indexer_v1_indexer_proto_rawDescData
}

var file_api_proto_indexer_v1_indexer_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_indexer_v1_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_proto_indexer_v1_indexer_proto_goTypes = []any{
	(ChainType)(0),                            // 0: indexer.v1.ChainType
	(ChainStatus)(0),                          // 1: indexer.v1.ChainStatus
	(TransactionStatus)(0),                    // 2: indexer.v1.TransactionStatus
	(*Chain)(nil),                             // 3: indexer.v1.Chain
	(*Block)(nil),                             // 4: indexer.v1.Block
	(*Transaction)(nil),                       // 5: indexer.v1.Transaction
	(*Log)(nil),                               // 6: indexer.v1.Log
	(*Progress)(nil),                          // 7: indexer.v1.Progress
	(*Gap)(nil),                               // 8: indexer.v1.Gap
	(*Stats)(nil),                             // 9: indexer.v1.Stats
	(*PageInfo)(nil),                          // 10: indexer.v1.PageInfo
	(*GetChainRequest)(nil),                   // 11: indexer.v1.GetChainRequest
	(*GetChainResponse)(nil),                  // 12: indexer.v1.GetChainResponse
	(*ListChainsRequest)(nil),                 // 13: indexer.v1.ListChainsRequest
	(*ListChainsResponse)(nil),                // 14: indexer.v1.ListChainsResponse
	(*GetBlockRequest)(nil),                   // 15: indexer.v1.GetBlockRequest
	(*GetBlockResponse)(nil),                  // 16: indexer.v1.GetBlockResponse
	(*GetBlockByHashRequest)(nil),             // 17: indexer.v1.GetBlockByHashRequest
	(*GetBlockByHashResponse)(nil),            // 18: indexer.v1.GetBlockByHashResponse
	(*ListBlocksRequest)(nil),                 // 19: indexer.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),                // 20: indexer.v1.ListBlocksResponse
	(*GetLatestBlockRequest)(nil),             // 21: indexer.v1.GetLatestBlockRequest
	(*GetLatestBlockResponse)(nil),            // 22: indexer.v1.GetLatestBlockResponse
	(*GetTransactionRequest)(nil),             // 23: indexer.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),            // 24: indexer.v1.GetTransactionResponse
	(*ListTransactionsByBlockRequest)(nil),    // 25: indexer.v1.ListTransactionsByBlockRequest
	(*ListTransactionsByBlockResponse)(nil),   // 26: indexer.v1.ListTransactionsByBlockResponse
	(*ListTransactionsByAddressRequest)(nil),  // 27: indexer.v1.ListTransactionsByAddressRequest
	(*ListTransactionsByAddressResponse)(nil), // 28: indexer.v1.ListTransactionsByAddressResponse
	(*GetProgressRequest)(nil),                // 29: indexer.v1.GetProgressRequest
	(*GetProgressResponse)(nil),               // 30: indexer.v1.GetProgressResponse
	(*ListGapsRequest)(nil),                   // 31: indexer.v1.ListGapsRequest
	(*ListGapsResponse)(nil),                  // 32: indexer.v1.ListGapsResponse
	(*GetStatsRequest)(nil),                   // 33: indexer.v1.GetStatsRequest
	(*GetStatsResponse)(nil),                  // 34: indexer.v1.GetStatsResponse
	(*StreamBlocksRequest)(nil),               // 35: indexer.v1.StreamBlocksRequest
	(*StreamTransactionsRequest)(nil),         // 36: indexer.v1.StreamTransactionsRequest
	(*StreamProgressRequest)(nil),             // 37: indexer.v1.StreamProgressRequest
	(*timestamppb.Timestamp)(nil),             // 38: google.protobuf.Timestamp
}
var file_api_proto_indexer_v1_indexer_proto_depIdxs = []int32{
	0,  // 0: indexer.v1.Chain.chain_type:type_name -> indexer.v1.ChainType
	1,  // 1: indexer.v1.Chain.status:type_name -> indexer.v1.ChainStatus
	38, // 2: indexer.v1.Chain.last_updated:type_name -> google.protobuf.Timestamp
	0,  // 3: indexer.v1.Block.chain_type:type_name -> indexer.v1.ChainType
	38, // 4: indexer.v1.Block.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 5: indexer.v1.Block.transactions:type_name -> indexer.v1.Transaction
	38, // 6: indexer.v1.Block.indexed_at:type_name -> google.protobuf.Timestamp
	38, // 7: indexer.v1.Transaction.block_timestamp:type_name -> google.protobuf.Timestamp
	2,  // 8: indexer.v1.Transaction.status:type_name -> indexer.v1.TransactionStatus
	6,  // 9: indexer.v1.Transaction.logs:type_name -> indexer.v1.Log
	38, // 10: indexer.v1.Transaction.indexed_at:type_name -> google.protobuf.Timestamp
	38, // 11: indexer.v1.Progress.last_updated:type_name -> google.protobuf.Timestamp
	3,  // 12: indexer.v1.GetChainResponse.chain:type_name -> indexer.v1.Chain
	3,  // 13: indexer.v1.ListChainsResponse.chains:type_name -> indexer.v1.Chain
	4,  // 14: indexer.v1.GetBlockResponse.block:type_name -> indexer.v1.Block
	4,  // 15: indexer.v1.GetBlockByHashResponse.block:type_name -> indexer.v1.Block
	4,  // 16: indexer.v1.ListBlocksResponse.blocks:type_name -> indexer.v1.Block
	4,  // 17: indexer.v1.GetLatestBlockResponse.block:type_name -> indexer.v1.Block
	5,  // 18: indexer.v1.GetTransactionResponse.transaction:type_name -> indexer.v1.Transaction
	5,  // 19: indexer.v1.ListTransactionsByBlockResponse.transactions:type_name -> indexer.v1.Transaction
	5,  // 20: indexer.v1.ListTransactionsByAddressResponse.transactions:type_name -> indexer.v1.Transaction
	7,  // 21: indexer.v1.GetProgressResponse.progress:type_name -> indexer.v1.Progress
	8,  // 22: indexer.v1.ListGapsResponse.gaps:type_name -> indexer.v1.Gap
	9,  // 23: indexer.v1.GetStatsResponse.stats:type_name -> indexer.v1.Stats
	11, // 24: indexer.v1.IndexerService.GetChain:input_type -> indexer.v1.GetChainRequest
	13, // 25: indexer.v1.IndexerService.ListChains:input_type -> indexer.v1.ListChainsRequest
	15, // 26: indexer.v1.IndexerService.GetBlock:input_type -> indexer.v1.GetBlockRequest
	17, // 27: indexer.v1.IndexerService.GetBlockByHash:input_type -> indexer.v1.GetBlockByHashRequest
	19, // 28: indexer.v1.IndexerService.ListBlocks:input_type -> indexer.v1.ListBlocksRequest
	21, // 29: indexer.v1.IndexerService.GetLatestBlock:input_type -> indexer.v1.GetLatestBlockRequest
	23, // 30: indexer.v1.IndexerService.GetTransaction:input_type -> indexer.v1.GetTransactionRequest
	25, // 31: indexer.v1.IndexerService.ListTransactionsByBlock:input_type -> indexer.v1.ListTransactionsByBlockRequest
	27, // 32: indexer.v1.IndexerService.ListTransactionsByAddress:input_type -> indexer.v1.ListTransactionsByAddressRequest
	29, // 33: indexer.v1.IndexerService.GetProgress:input_type -> indexer.v1.GetProgressRequest
	31, // 34: indexer.v1.IndexerService.ListGaps:input_type -> indexer.v1.ListGapsRequest
	33, // 35: indexer.v1.IndexerService.GetStats:input_type -> indexer.v1.GetStatsRequest
	35, // 36: indexer.v1.IndexerService.StreamBlocks:input_type -> indexer.v1.StreamBlocksRequest
	36, // 37: indexer.v1.IndexerService.StreamTransactions:input_type -> indexer.v1.StreamTransactionsRequest
	37, // 38: indexer.v1.IndexerService.StreamProgress:input_type -> indexer.v1.StreamProgressRequest
	12, // 39: indexer.v1.IndexerService.GetChain:output_type -> indexer.v1.GetChainResponse
	14, // 40: indexer.v1.IndexerService.ListChains:output_type -> indexer.v1.ListChainsResponse
	16, // 41: indexer.v1.IndexerService.GetBlock:output_type -> indexer.v1.GetBlockResponse
	18, // 42: indexer.v1.IndexerService.GetBlockByHash:output_type -> indexer.v1.GetBlockByHashResponse
	20, // 43: indexer.v1.IndexerService.ListBlocks:output_type -> indexer.v1.ListBlocksResponse
	22, // 44: indexer.v1.IndexerService.GetLatestBlock:output_type -> indexer.v1.GetLatestBlockResponse
	24, // 45: indexer.v1.IndexerService.GetTransaction:output_type -> indexer.v1.GetTransactionResponse
	26, // 46: indexer.v1.IndexerService.ListTransactionsByBlock:output_type -> indexer.v1.ListTransactionsByBlockResponse
	28, // 47: indexer.v1.IndexerService.ListTransactionsByAddress:output_type -> indexer.v1.ListTransactionsByAddressResponse
	30, // 48: indexer.v1.IndexerService.GetProgress:output_type -> indexer.v1.GetProgressResponse
	32, // 49: indexer.v1.IndexerService.ListGaps:output_type -> indexer.v1.ListGapsResponse
	34, // 50: indexer.v1.IndexerService.GetStats:output_type -> indexer.v1.GetStatsResponse
	4,  // 51: indexer.v1.IndexerService.StreamBlocks:output_type -> indexer.v1.Block
	5,  // 52: indexer.v1.IndexerService.StreamTransactions:output_type -> indexer.v1.Transaction
	7,  // 53: indexer.v1.IndexerService.StreamProgress:output_type -> indexer.v1.Progress
	39, // [39:54] is the sub-list for method output_type
	24, // [24:39] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_proto_indexer_v1_indexer_proto_init() }
func file_api_proto_indexer_v1_indexer_proto_init() {
	if File_api_proto_indexer_v1_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_indexer_v1_indexer_proto_rawDesc), len(file_api_proto_indexer_v1_indexer_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_indexer_v1_indexer_proto_goTypes,
		DependencyIndexes: file_api_proto_indexer_v1_indexer_proto_depIdxs,
		EnumInfos:         file_api_proto_indexer_v1_indexer_proto_enumTypes,
		MessageInfos:      file_api_proto_indexer_v1_indexer_proto_msgTypes,
	}.Build()
	File_api_proto_indexer_v1_indexer_proto = out.File
	file_api_proto_indexer_v1_indexer_proto_goTypes = nil
	file_api_proto_indexer_v1_indexer_proto_depIdxs = nil
}
