# XRP Ledger (Ripple) Indexer Configuration

# Storage configuration
storage:
  type: pebble
  path: ./data/pebble

# Chain configuration
chains:
  - chain_id: "xrpl-mainnet"
    chain_name: "XRP Ledger"
    network: "mainnet"
    chain_type: "ripple"

    # XRP Ledger RPC endpoint
    rpc_url: "https://xrplcluster.com"

    # WebSocket endpoint
    websocket_url: "wss://xrplcluster.com"

    # Connection settings
    timeout: 30s
    retry_attempts: 3
    retry_delay: 1s
    max_connections: 10

    # Indexing settings
    batch_size: 100
    start_ledger: 0

    # WebSocket settings
    enable_websocket: false

    # XRP Ledger specific settings
    include_transaction_metadata: true

# Server configuration
server:
  host: "0.0.0.0"
  http_port: 8080
  grpc_port: 50051

  # TLS configuration (optional)
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics configuration
metrics:
  enabled: true
  host: "0.0.0.0"
  port: 9091
  path: "/metrics"

# Event bus configuration
event_bus:
  queue_size: 10000
  workers: 10
  retry_attempts: 3
  retry_delay: 1s

# ================================
# Alternative XRP Ledger Endpoints
# ================================

# Testnet Configuration
# chains:
#   - chain_id: "xrpl-testnet"
#     chain_name: "XRP Ledger Testnet"
#     network: "testnet"
#     chain_type: "ripple"
#     rpc_url: "https://s.altnet.rippletest.net:51234"
#     websocket_url: "wss://s.altnet.rippletest.net:51233"
#     include_transaction_metadata: true
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# Devnet Configuration
# chains:
#   - chain_id: "xrpl-devnet"
#     chain_name: "XRP Ledger Devnet"
#     network: "devnet"
#     chain_type: "ripple"
#     rpc_url: "https://s.devnet.rippletest.net:51234"
#     websocket_url: "wss://s.devnet.rippletest.net:51233"
#     include_transaction_metadata: true
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# Alternative Mainnet Endpoints
# chains:
#   - chain_id: "xrpl-mainnet-alt"
#     chain_name: "XRP Ledger (Ripple Public)"
#     network: "mainnet"
#     chain_type: "ripple"
#     rpc_url: "https://s1.ripple.com:51234"
#     websocket_url: "wss://s1.ripple.com"
#     include_transaction_metadata: true
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# Local rippled Node
# chains:
#   - chain_id: "xrpl-local"
#     chain_name: "XRP Ledger Local"
#     network: "local"
#     chain_type: "ripple"
#     rpc_url: "http://localhost:5005"
#     websocket_url: "ws://localhost:6006"
#     include_transaction_metadata: true
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# Note: Full implementation of XRP Ledger indexing requires:
# - ledger method for fetching ledgers
# - tx method for fetching transactions
# - account_tx for fetching account transactions
# - subscribe/unsubscribe for real-time updates
# - Proper handling of XRP Ledger specific data structures
# Current implementation provides basic structure and configuration
