# Avalanche Chain Indexer Configuration

# Storage configuration
storage:
  type: pebble
  path: ./data/pebble

# Chain configuration
chains:
  - chain_id: "avalanche-c"
    chain_name: "Avalanche C-Chain"
    network: "mainnet"
    chain_type: "avalanche"

    # Avalanche C-Chain RPC endpoint (EVM compatible)
    rpc_url: "https://api.avax.network/ext/bc/C/rpc"

    # WebSocket endpoint
    ws_url: "wss://api.avax.network/ext/bc/C/ws"

    # Connection settings
    timeout: 30s
    retry_attempts: 3
    retry_delay: 1s
    max_connections: 10

    # Indexing settings
    batch_size: 100
    start_block: 0

    # WebSocket settings
    enable_websocket: false

    # Avalanche-specific settings
    avalanche_chain_type: "C-Chain"  # C-Chain, X-Chain, or P-Chain

# Server configuration
server:
  host: "0.0.0.0"
  http_port: 8080
  grpc_port: 50051

  # TLS configuration (optional)
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics configuration
metrics:
  enabled: true
  host: "0.0.0.0"
  port: 9091
  path: "/metrics"

# Event bus configuration
event_bus:
  queue_size: 10000
  workers: 10
  retry_attempts: 3
  retry_delay: 1s

# ================================
# Alternative Avalanche Chain Examples
# ================================

# Fuji Testnet C-Chain Configuration
# chains:
#   - chain_id: "avalanche-fuji-c"
#     chain_name: "Avalanche Fuji C-Chain"
#     network: "testnet"
#     chain_type: "avalanche"
#     rpc_url: "https://api.avax-test.network/ext/bc/C/rpc"
#     ws_url: "wss://api.avax-test.network/ext/bc/C/ws"
#     avalanche_chain_type: "C-Chain"
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# Local Avalanche Node C-Chain Configuration
# chains:
#   - chain_id: "avalanche-local-c"
#     chain_name: "Avalanche Local C-Chain"
#     network: "local"
#     chain_type: "avalanche"
#     rpc_url: "http://localhost:9650/ext/bc/C/rpc"
#     ws_url: "ws://localhost:9650/ext/bc/C/ws"
#     avalanche_chain_type: "C-Chain"
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# X-Chain Configuration (Future Support)
# chains:
#   - chain_id: "avalanche-x"
#     chain_name: "Avalanche X-Chain"
#     network: "mainnet"
#     chain_type: "avalanche"
#     rpc_url: "https://api.avax.network/ext/bc/X"
#     avalanche_chain_type: "X-Chain"
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100

# P-Chain Configuration (Future Support)
# chains:
#   - chain_id: "avalanche-p"
#     chain_name: "Avalanche P-Chain"
#     network: "mainnet"
#     chain_type: "avalanche"
#     rpc_url: "https://api.avax.network/ext/bc/P"
#     avalanche_chain_type: "P-Chain"
#     timeout: 30s
#     retry_attempts: 3
#     batch_size: 100
